### ISSUE TITLE
TODO: Upgrades after typescript support.

### ISSUE THREAD

**Issue by pradyuman-verma** [Instadapp/dsa-connectors#129]
Things to implement after #123  gets merged.

- [x]  Make deployment script interactive, use command line args to pass data to deployment script.
- [x] Upgrade `test:runner` script, enable usage of command line args to pass data. https://github.com/Instadapp/dsa-connectors/pull/200
- [x] add other chain support to `addLiquidity` script.
- [x] script to Verify contract after deployment, use `sourcify` and `hardhat-etherscan.`
- [ ] Upgrade solidity version of contract, maybe to 0.8.6.
- [ ] Explain any one connector test case in detail, as it will be helpful for understanding underlying code.
- [x] Add `SPDX-License-Identifier:` in solidity files. https://github.com/Instadapp/dsa-connectors/pull/199
